# Generated by Django 5.0.3 on 2024-03-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.IntegerField(choices=[
                 (1, 'ECONOMIC'), (2, 'STANDARD'), (3, 'PREMIUM'), (4, 'LUXURY')], verbose_name='Тип комнаты')),
                ('spots', models.IntegerField(verbose_name='Количество мест')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=7, verbose_name='Цена за день')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
            },
        ),
    ]
