version: '3.10'

services:

  web:
    build: .
    ports:
      - "8000:8000"
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    networks:
      - net
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      net:

#  test_db:
#    image: postgres:13
#    volumes:
#      - postgres_data_test:/var/lib/postgresql/data
#    env_file:
#      - .env
#    ports:
#      - 5432:5432
#    networks:
#      net:

volumes:
  postgres_data:
#  postgres_data_test:
networks:
  net:
