version: '3.10'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  test_db:
    image: postgres:13
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

volumes:
  postgres_data:
  postgres_data_test:
