# Generated by Django 5.0.3 on 2024-03-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Бронь', 'verbose_name_plural': 'Брони'},
        ),
        migrations.AddField(
            model_name='booking',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
